#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob globstar

HOSTNAME=
HOSTED_ZONE_ID=
# user:password
TOKEN=
INTERVAL=60 # seconds

export AWS_SHARED_CREDENTIALS_FILE=aws-credentials
IP_FILE=ip.txt
URL=http://"$HOSTNAME/health-check"


function health_check() {
  RES=$(curl "$URL" --user "$TOKEN" --max-time 0.5 --silent)
  IP=$(cat $IP_FILE)
  if [ "$RES" == "$IP" ]; then
    log "OK"
  else
    log "FAILED. Checking DNS."
    update_dns
  fi
}

function update_dns() {
  IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
  LAST_IP=$(cat $IP_FILE)
  if [ "$IP" == "$LAST_IP" ]; then
    log "DNS is up to date. IP is $IP."
  else
    log "Updating DNS from $LAST_IP to $IP."
    aws route53 change-resource-record-sets \
      --hosted-zone-id "$HOSTED_ZONE_ID" \
      --change-batch "$(cat <<JSON
  {
    "Comment": "Update $HOSTNAME DNS",
    "Changes": [
      {
        "Action": "UPSERT",
        "ResourceRecordSet": {
          "Name": "$HOSTNAME",
          "Type": "A",
          "TTL": 60,
          "ResourceRecords": [
            {
              "Value": "$IP"
            }
          ]
        }
      }
    ]
  }
JSON
      )"
    echo "$IP" >| "$IP_FILE"
    log "DNS updated from $LAST_IP to $IP."
  fi
}

function log() {
  echo "[Health Check]" - "$(date)" - "$1"
}

log "Starting."
while sleep "$INTERVAL"; do health_check; done
